Fix issues and add redirection on reservations page
VladimirV99/Projektor pull request #138
Opened 2022-06-29 09:31 UTC by Hos1g4k1

2022-07-01 20:56 UTC, VladimirV99 requested changes

2022-07-01 20:56 UTC, VladimirV99 commented on app/src/features/ReservationDetailsScreen/index.tsx
> +                )}
Da li se dugme za rezervisanje vidi ako korisnik nije ulogovan? Ako da, mozes li da mu dodas uslov `currentUser &&`

Takodje, mozes ovde da sklonis uslov `numberOfSelectedSeats > 0`. Neka se poruka uvek vidi

2022-07-01 20:56 UTC, VladimirV99 commented on app/src/features/ReservationDetailsScreen/index.tsx
> +                )}
Zapravo, fali nam i provera `isUserCustomer`. Ako nije, postavi dugme na disabled. Ima u `util/auth` pomocna funkcija koja to proverava

2022-07-02 18:11 UTC, VladimirV99 approved these changes

2022-07-02 18:41 UTC, aleksakojadinovic approved these changes

2022-07-02 19:21 UTC, merged