Feature screening service
VladimirV99/Projektor pull request #56
Opened 2022-05-05 13:18 UTC by Hos1g4k1

2022-05-05 14:01 UTC, VladimirV99 requested changes
Ostalo je jos dopuniti README i dodati podrsku za gateway, ali to moze u nekom drugom PR

2022-05-05 14:17 UTC, aleksakojadinovic commented on Services/Screening/Data/IScreeningRepository.cs
> +		public bool DeleteMovie(int id);
valjda ne mozes u interfejsu da stavis async?

2022-05-05 14:18 UTC, aleksakojadinovic commented on Services/Screening/Data/ScreeningRepository.cs
> +        async Task<List<Entities.Screening>> IScreeningRepository.GetScreenings()
sto ne uradis
```using Entities```
ili sta vec da ne bi morao stavi put ```Entites.nesto```

2022-05-05 14:22 UTC, aleksakojadinovic commented on Services/Screening/Data/ScreeningRepository.cs
> +        public Entities.Screening? GetScreeningByHallIdInSpecificMoment(int id, DateTime moment)
Mogao si ovu i ```GetScreeningByHallId``` funkciju da spojis u jednu koja prima neki ```GetScreeningRequest``` gde imas ```int? id``` i ```DateTime? moment``` i onda ako je nesto null iskuliras ga a ako nije onda trazis po tome

2022-05-05 19:33 UTC, VladimirV99 requested changes

2022-05-05 19:33 UTC, VladimirV99 commented on Services/Screening/Controllers/ScreeningController.cs
> +        public async Task<IActionResult> GetScreenings()
Ostalo je jos funkcija bez ispravnog tipa povratne vrednosti

2022-05-05 19:33 UTC, VladimirV99 commented on Services/Screening/Controllers/ScreeningController.cs
> +        public async Task<bool> InsertScreening(int hallId, int movieId, DateTime moment)
Hocemo li da koristimo `Task<IActionResult>` umesto `Task<bool>`, tj. da dobijamo npr. NotFound ili Ok umesto true/false?

2022-05-05 19:33 UTC, VladimirV99 commented on Services/Screening/Controllers/ScreeningController.cs
> +        public async Task<bool> InsertScreening(int hallId, int movieId, DateTime moment)
Isto vazi za narednih nekoliko funkcija

2022-05-06 09:26 UTC, aleksakojadinovic commented on Services/Screening/Models/ScreeningModel.cs
> +        public Movie Movie { get; set; }
zar ne bi trebao MovieModel da bude ovde?

2022-05-06 09:27 UTC, aleksakojadinovic commented on Services/Screening/Models/ScreeningModel.cs
> +        public Movie Movie { get; set; }
Trebalo bi da automapper to ume sam da regulise

2022-05-06 09:42 UTC, VladimirV99 approved these changes

2022-05-06 12:25 UTC, merged