Implement access token authentication
VladimirV99/Projektor pull request #8
Opened 2022-03-19 17:53 UTC by VladimirV99

Closes #4

2022-03-19 18:03 UTC, aleksakojadinovic requested changes

2022-03-19 18:03 UTC, aleksakojadinovic commented on Security/Identity/Controllers/UserController.cs
> +                return Ok(_mapper.Map<UserDetails>(user));
early returnnnn

2022-03-19 18:03 UTC, aleksakojadinovic commented on Security/Identity/Controllers/UserController.cs
> +            return NotFound();
opet early return

2022-03-19 18:03 UTC, aleksakojadinovic commented on Security/Identity/Swagger/AuthOperationFilter.cs
> +            {
aj nek bude i ovde early return :DD

2022-03-20 20:18 UTC, aleksakojadinovic commented on Security/Identity/Controllers/AdministratorController.cs
> +        }
stavi ove greske u konstante :D

2022-03-20 20:25 UTC, Hos1g4k1 approved these changes

2022-03-20 21:35 UTC, aleksakojadinovic approved these changes

2022-03-20 21:35 UTC, merged