Screening fixes
VladimirV99/Projektor pull request #83
Opened 2022-05-17 15:34 UTC by Hos1g4k1

Ostaje ovaj Auth todo. Njega cu da resavam kada budem dodavao metode koje ce mi trebati za admin dashboard pa u jednom prolazu sve

2022-05-17 16:19 UTC, VladimirV99 requested changes

2022-05-17 16:19 UTC, VladimirV99 commented on Services/Screening/Controllers/ScreeningController.cs
> +            var hall = await _repository.GetHallById(id);
treba nam NotFound provera

2022-05-17 16:19 UTC, VladimirV99 commented on Services/Screening/Controllers/ScreeningController.cs
> +        [ProducesResponseType(StatusCodes.Status404NotFound)]
ova anotacija nije potrebna

2022-05-17 16:19 UTC, VladimirV99 commented on Services/Screening/Entities/Screening.cs
>  		public int HallId { get; set; }
mozes li da dodas ovde i u modelu Hall objekat pa da radis include u repozitorijumu gde treba da se vrati korisniku

2022-05-17 20:50 UTC, aleksakojadinovic commented on Services/Screening/Models/GetScreeningsByHallIdAtTimeRequest.cs
> +    public class GetScreeningsByHallIdAtTimeRequest
Ovo neki blizak rodjak AbstractSingletonProxyFactoryBean-a

2022-05-17 20:52 UTC, aleksakojadinovic approved these changes

2022-05-21 08:14 UTC, VladimirV99 approved these changes

2022-05-21 08:14 UTC, merged