Reservation service
VladimirV99/Projektor pull request #94
Opened 2022-05-22 12:44 UTC by Hos1g4k1

2022-05-22 13:04 UTC, aleksakojadinovic requested changes

2022-05-22 13:04 UTC, aleksakojadinovic commented on ApiGateways/WebGateway/ocelot.Development.json
> +      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ]
dodaj i Options u metode odma, jer kad tad ce da ti pukne :D

2022-05-22 13:04 UTC, aleksakojadinovic commented on ApiGateways/WebGateway/ocelot.Local.json
> +      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ]
isto Options i ovde

2022-05-22 13:24 UTC, VladimirV99 approved these changes

2022-05-23 13:59 UTC, aleksakojadinovic approved these changes

2022-05-23 20:34 UTC, merged